name: Test webhook

on:
  push:
    branches: ["master"]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: "http://31.14.17.154:8000/reload-solana-speedrun/${{ secrets.DEPLOY_KEY }}"
          method: "GET"
